name: 'Rudor SBOM Scanner'
description: 'Generate Software Bill of Materials (SBOM) and scan for vulnerabilities using Rudor'
author: 'iron-kite'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  path:
    description: 'Path to the project directory to scan'
    required: false
    default: '.'

  output:
    description: 'Output file path for the SBOM'
    required: false
    default: 'bom.json'

  project-type:
    description: 'Project type (auto-detected if not specified). Examples: dotnet, nodejs, python, java, go, rust'
    required: false
    default: ''

  disable-cve:
    description: 'Disable automatic CVE vulnerability scanning'
    required: false
    default: 'false'

  verbose:
    description: 'Enable verbose output for debugging'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/iron-kite/rudor:latest'
  args:
    - generate
    - ${{ inputs.path }}
    - -o
    - ${{ inputs.output }}
    - ${{ inputs.project-type && format('-t {0}', inputs.project-type) || '' }}
    - ${{ inputs.verbose == 'true' && '-v' || '' }}
    - ${{ inputs.disable-cve == 'true' && '--no-cve' || '' }}