package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	cdx "github.com/CycloneDX/cyclonedx-go"
)

func generateSBOM(projectPath, projType string, verbose bool) (bom *cdx.BOM, err error) {
	var cachedBinaryPath string
	defer func() {
		if err == nil {
			return
		}

		if cachedBinaryPath != "" && fileExists(cachedBinaryPath) {
			if err := os.Remove(cachedBinaryPath); err != nil && verbose {
				fmt.Printf("⚠️ Warning: Could not delete temporary file %s: %v\n", cachedBinaryPath, err)
			}
		}
	}()

	// Convert to absolute path
	absolutePath, err := filepath.Abs(projectPath)
	if err != nil {
		return nil, fmt.Errorf("failed to get absolute path: %w", err)
	}

	// Check if path exists
	if !fileExists(absolutePath) && !dirExists(absolutePath) {
		return nil, fmt.Errorf("path does not exist: %s", absolutePath)
	}

	fmt.Printf("🔍 Generating SBOM for: %s\n", absolutePath)

	// Extract embedded binary to cache (or use cached version)
	cachedBinaryPath, err = extractEmbeddedBinary(verbose)
	if err != nil {
		return nil, fmt.Errorf("failed to extract embedded binary: %w", err)
	}

	// Create temporary file for cdxgen output
	tempBOMFile, err := os.CreateTemp("", "rudor-bom-*.json")
	if err != nil {
		return nil, fmt.Errorf("failed to create temporary BOM file: %w", err)
	}
	tempBOMPath := tempBOMFile.Name()
	tempBOMFile.Close()

	// Ensure cleanup of temporary BOM file
	defer func() {
		if err := os.Remove(tempBOMPath); err != nil && verbose {
			fmt.Printf("⚠️ Warning: Could not delete temporary BOM file %s: %v\n", tempBOMPath, err)
		}
	}()

	// Build cdxgen arguments using the temporary file
	args := []string{"-o", tempBOMPath}

	// Add project type if specified
	if projType != "" {
		args = append(args, "-t", projType)
	}

	// Add the path to scan at the end
	args = append(args, absolutePath)

	if verbose {
		fmt.Printf("Running: %s %s\n", cachedBinaryPath, strings.Join(args, " "))
	}

	if verbose {
		fmt.Printf("🔧 Using temporary BOM file: %s\n", tempBOMPath)
	}

	// Execute cdxgen
	cmd := exec.Command(cachedBinaryPath, args...)

	if verbose {
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
	}

	if err := cmd.Run(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			return nil, fmt.Errorf("cdxgen failed with exit code: %d", exitErr.ExitCode())
		}
		return nil, fmt.Errorf("failed to execute cdxgen: %w", err)
	}

	// Check if temporary BOM file was created
	if !fileExists(tempBOMPath) {
		return nil, fmt.Errorf("SBOM file was not generated by cdxgen")
	}

	// Enhance the BOM with Rudor metadata and return it
	bom, err = enhanceBOM(tempBOMPath, verbose)
	if err != nil {
		return nil, fmt.Errorf("failed to enhance BOM: %w", err)
	}

	fmt.Printf("✅ SBOM generated successfully\n")
	return bom, nil
}

func extractEmbeddedBinary(verbose bool) (string, error) {
	binaryData, binaryName, err := getEmbeddedBinary()
	if err != nil {
		return "", err
	}

	// Build versioned cache filename (e.g., cdxgen-1.0.0.exe)
	extension := filepath.Ext(binaryName)
	cachedFileName := fmt.Sprintf("cdxgen-%s%s", version, extension)
	cachedPath := filepath.Join(os.TempDir(), cachedFileName)

	// Check if cached binary already exists
	if fileExists(cachedPath) {
		if verbose {
			fmt.Printf("✅ Using cached binary: %s\n", cachedPath)
		}
		return cachedPath, nil
	}

	if verbose {
		fmt.Printf("🔧 Extracting embedded binary: %s\n", binaryName)
	}

	// Write embedded binary to cache
	if err := os.WriteFile(cachedPath, binaryData, 0755); err != nil {
		return "", fmt.Errorf("failed to write binary to cache: %w", err)
	}

	// Make executable on Unix-like systems
	if runtime.GOOS != "windows" {
		if err := os.Chmod(cachedPath, 0755); err != nil {
			return "", fmt.Errorf("failed to make binary executable: %w", err)
		}
	}

	if verbose {
		fmt.Printf("✅ Binary cached to: %s\n", cachedPath)
	}

	return cachedPath, nil
}

func getEmbeddedBinary() ([]byte, string, error) {
	return embeddedBinary, binaryName, nil
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

// enhanceBOM reads a BOM from inputPath, enhances it with Rudor metadata, and returns it
func enhanceBOM(inputPath string, verbose bool) (*cdx.BOM, error) {
	if verbose {
		fmt.Println("🔧 Enhancing BOM with Rudor metadata...")
	}

	// Read the existing BOM file
	inputFile, err := os.Open(inputPath)
	if err != nil {
		return nil, fmt.Errorf("failed to open SBOM file: %w", err)
	}
	defer inputFile.Close()

	// Decode the BOM
	bom := new(cdx.BOM)
	decoder := cdx.NewBOMDecoder(inputFile, cdx.BOMFileFormatJSON)
	if err := decoder.Decode(bom); err != nil {
		return nil, fmt.Errorf("failed to decode SBOM: %w", err)
	}

	// Initialize metadata if it doesn't exist
	if bom.Metadata == nil {
		bom.Metadata = &cdx.Metadata{}
	}

	// Initialize tools if it doesn't exist
	if bom.Metadata.Tools == nil {
		bom.Metadata.Tools = &cdx.ToolsChoice{}
	}

	// Create Rudor component with dynamic information
	appName := getBinaryName()
	orgName := "Iron Kite"
	email := "info@ironkite.com"

	rudorComponent := &cdx.Component{
		Type:      cdx.ComponentTypeApplication,
		Name:      appName,
		Version:   version,
		Publisher: orgName,
		Authors: &[]cdx.OrganizationalContact{
			{
				Name:  orgName,
				Email: email,
			},
		},
	}

	// Add rudor component to BOM metadata tools
	if bom.Metadata.Tools.Components == nil {
		bom.Metadata.Tools.Components = &[]cdx.Component{*rudorComponent}
	} else {
		// Check if our tool already exists and update it, or add it
		found := false
		for i, component := range *bom.Metadata.Tools.Components {
			if component.Name == appName {
				(*bom.Metadata.Tools.Components)[i] = *rudorComponent
				found = true
				break
			}
		}
		if !found {
			*bom.Metadata.Tools.Components = append(*bom.Metadata.Tools.Components, *rudorComponent)
		}
	}

	if verbose {
		fmt.Printf("✅ BOM enhanced with %s metadata\n", appName)
	}

	return bom, nil
}

// saveBOM saves a BOM struct to the specified file path
func saveBOM(bom *cdx.BOM, outputPath string, verbose bool) error {
	if verbose {
		fmt.Printf("💾 Saving SBOM to: %s\n", outputPath)
	}

	// Create output file
	outputFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer outputFile.Close()

	// Encode the BOM
	encoder := cdx.NewBOMEncoder(outputFile, cdx.BOMFileFormatJSON)
	encoder.SetPretty(true)

	if err := encoder.Encode(bom); err != nil {
		return fmt.Errorf("failed to encode SBOM: %w", err)
	}

	absoluteOutput, err := filepath.Abs(outputPath)
	if err != nil {
		absoluteOutput = outputPath
	}

	fmt.Printf("✅ SBOM saved successfully: %s\n", absoluteOutput)
	return nil
}

// getBinaryName extracts the binary name from os.Args[0]
func getBinaryName() string {
	binaryPath := os.Args[0]
	binaryName := filepath.Base(binaryPath)

	// Remove .exe extension on Windows
	if runtime.GOOS == "windows" {
		if ext := filepath.Ext(binaryName); ext == ".exe" {
			binaryName = strings.TrimSuffix(binaryName, ext)
		}
	}

	return binaryName
}
